### ISSUE TITLE
E11000 duplicate key error collection: adexRelayer.identity index: address_1_privileges_1 dup key: 

### ISSUE THREAD

**Issue by AndreiD** [AdExNetwork/adex-dapp#129]
![image](https://user-images.githubusercontent.com/542665/62471051-7495ba80-b7a4-11e9-962b-7674701d5eb5.png)

gives 

~~~~
{"driver":true,"name":"MongoError","index":0,"code":11000,"errmsg":"E11000 duplicate key error collection: adexRelayer.identity index: address_1_privileges_1 dup key: { : \"0x5318f5d7683964055ba5d1077cd24ab1fd88f4e6\", : \"0x6C34966fdB7222Ee90D7E1424967aBd4D0d96e33\" }"}
~~~~

some unique key constraints I presume.

**Comment by IvoPaunov** [comment]
Do you have access code for registering standard account in production?
You need this because it does not work properly at the moment - (also you need to have some ETH on the wallet that will sign the identity creation transaction).
It will be fixed when [counterfactual accounts](https://github.com/AdExNetwork/adex-dapp/issues/78) are ready.

It looks that you have tried to generate "Generate full identity deploy data" for more than one time with the same identity which should not be possible. It looks like bug int the steps state.

Can you confirm that I'm right for what you are doing

**Comment by IvoPaunov** [comment]
Found the bug ant actually it will be fixed with [counterfactual accounts](https://github.com/AdExNetwork/adex-dapp/issues/78).
If you want try the platform, I can send you code for grant account on the mail of the screenshot.

**Comment by AndreiD** [comment]
all right. send the code there, and delete this issue if you can. I'll take a look tomorrow....
