### ISSUE TITLE
Minor bugs

### ISSUE THREAD

**Issue by ahaghdan** [AdExNetwork/adex-dapp#22]
Bug1: Archive Campaign dialog button "No" is missing an N so it displays "o". Please see screenshot here: https://imgur.com/a/Arf9QqO.

Bug2: Create new ad slot wizard crop feature turns avatar image or fallback image to black if the image has transparency. Please see screenshots here: https://imgur.com/a/vjtpsPJ

**Comment by IvoPaunov** [comment]
Thank you for the bug report. Sorry for the late answer. The typo will be fixed in the next release. About the crop bug - I was aware of that but there was no time for fixing it. Now I'm thinking to let only .jpeg, .jpg for uploading because if you have transparency and you can not control the background it can bring you a lot of trouble. For instance last week I've made reservation for some move theater and they send me email with .png with black bar code on transparent background. Then when a had to show the bar code at the entrance I couldn't because all app on my phone that can open images have black background. In your case with ad slot this will not be a big problem but for ad units will be because the image is you banner.

Let me know if you think the ability to upload images with transparency have a real use case for you or to disable it with the next release.

**Comment by ahaghdan** [comment]
I think we should disable the transparency upload feature for now, it is a complicated scenario and can be added later if required.

**Comment by IvoPaunov** [comment]
Fixed in v2.1.6
